ems 3.37 mc4plus 3.30 mc2plus 2.21
robotology/icub-firmware-build pull request #24
Opened 2021-03-16 18:38 UTC by AlexAntn

This PR comes in the sequence of the now-merged [https://github.com/robotology/icub-firmware/pull/170](https://github.com/robotology/icub-firmware/pull/170), adding the builds for the three mentioned boards (ems, mc2plus and mc4plus).

This PR introduces a counter that limits the number of error messages due to dirty or broken-phase encoders, in order to prevent the saturation of yarplogger in such cases.

In addition, when/if the error goes away, it sends an info message (value `eoerror_value_MC_motor_qencoder_phase_disappeared`) informing the user that the error disappeared and resets the error message counter.

2021-03-16 20:57 UTC, pattacini approved these changes

2021-03-17 16:47 UTC, marcoaccame requested changes
Hi @AlexAntn,

can you please integrate the log w/ info of how you built the binaries and what are the main changes respect to previous version?

Something as in [here](https://github.com/robotology/icub-firmware-build/commit/dec92746323835ae6c73e2dbd7af7c50237d32f6).

2021-03-17 21:26 UTC, pattacini commented
@marcoaccame actually, I think that since the changes are introduced via PR (which points other PR's) the information is already contained in the description above, which can be certainly completed/extended with the missing pieces.

2021-03-18 08:18 UTC, marcoaccame commented
> The commit resulting from the merge will automatically contain a comment pointing to this PR.
hi @pattacini, we can do that.

2021-03-18 08:18 UTC, marcoaccame approved these changes

2021-03-18 08:19 UTC, merged