Following PR:https://github.com/robotology/icub-firmware/pull/182 and…
robotology/icub-firmware-build pull request #27
Opened 2021-04-27 14:59 UTC by triccyx

Following modifications in:
PR:https://github.com/robotology/icub-firmware/pull/182
PR:https://github.com/robotology/icub-firmware/pull/180

2021-04-27 15:11 UTC, pattacini approved these changes

2021-04-30 12:22 UTC, pattacini commented
@marcoaccame any updates on this review?

2021-05-03 10:09 UTC, marcoaccame requested changes
Hi @triccyx,
pls change also the application version of the strain2 in file https://github.com/robotology/icub-firmware-build/blob/devel/info/firmware.info.xml#L107 which is used by the automatic FW update procedure.

2021-05-03 14:02 UTC, marcoaccame approved these changes
ok. thanks @triccyx

2021-05-03 14:07 UTC, merged